### ISSUE TITLE
todos & bugs

### ISSUE THREAD

**Issue by SamMcSam** [SamMcSam/chifoumi-championship#3]
### Todos 
- [ ] `lobby.js` set status of players who lost in lobby.users
- [ ] play next round
- [ ] stop game when only you left
- [ ] finish game : win, lose

### Bugs 
- [ ] bug quit while playing, list not reload
- [ ] display next play is wrong?/weird
- [ ] bug player lost
- [ ] bug? message waiting
